[package]
name = "briefly"
authors = ["adrianEffe <adrian.iosdev@gmail.com>"]
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
axum = "0.6.1"
tokio = { version = " 1.28.2", features = ["macros", "rt-multi-thread"] }
